# Generated by Django 4.1.1 on 2022-09-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athenaeum', '0004_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='linkToBuy',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
