# Generated by Django 3.2.15 on 2022-10-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athenaeum', '0005_book_linktobuy_book_price_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='ispn',
            field=models.TextField(blank=True, default='', max_length=13),
        ),
    ]
