# Generated by Django 4.1.1 on 2022-10-06 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athenaeum', '0006_auto_20221003_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isInStock',
            new_name='is_in_stock',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='linkToBuy',
            new_name='link_to_buy',
        ),
    ]
