# Generated by Django 4.1.1 on 2022-10-09 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athenaeum', '0007_rename_isinstock_book_is_in_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ispn',
            new_name='isbn',
        ),
    ]
